# Supabase Session Pooler Connection
spring.datasource.url=jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:5432/postgres?user=postgres.rwwidgdpwfmnxprogzef&password=samit@0714@@##
spring.datasource.username=postgres.rwwidgdpwfmnxprogzef
spring.datasource.password=samit@0714@@##
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=8080